### ISSUE TITLE
Rename this repo!

### ISSUE THREAD

**Issue by XaviTorello** [gisce/hookshub#11]
To ensure a correct indexation and positioning

**Comment by jaumef** [comment]
@XaviTorello @ecarreras 
Some names:
- [x] hookshub
- [ ] hook-listener
- [ ] webhooks
- [ ] webhooks-dispatcher
- [ ] hooks
- [ ] hook-dristribution
- [ ] hook-parser
- [ ] hook-dealer

**Comment by XaviTorello** [comment]
@jaumef hookshub +1

What about webhooks-dispatcher?
