### ISSUE TITLE
All actions inside one unique directory

### ISSUE THREAD

**Issue by XaviTorello** [gisce/hookshub#18]
Instead of 

```
/hooks
  /gitlab
  /github
  ....
```

use

```
/hooks/
  github_00_X0
  gitlab_00_X0
  gitlab_01_X1
  ....
```

**Comment by jaumef** [comment]
And the naming format?

```
origin_event-code_action-num
```

Or what about moduling the actions into a class?

**Comment by jaumef** [comment]
I think actions are great for method testing, but we should better implement hooks as defined on PR #66
