### ISSUE TITLE
Powerp-docs - Compile pofile before mkdocs build

### ISSUE THREAD

**Issue by jaumef** [gisce/hookshub#53]
When skipping *.mo file to be commited, even if you translated a lot of strings, the build process does not update the *.mo file.

It could be pretty interesting to compile the *.po file into *.mo file before building mkdocs.

**Comment by ecarreras** [comment]
Why you closed this issue? exists this problem?

**Comment by jaumef** [comment]
Moved to https://github.com/gisce/powerp-docs/issues/72 as an external issue.

I should have written there first...
